org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.useSystemProxies=false -Dhttp.proxyHost= -Dhttps.proxyHost= -DsocksProxyHost= -DsocksProxyPort=0
systemProp.java.net.useSystemProxies=false
systemProp.http.proxyHost=
systemProp.https.proxyHost=
systemProp.socksProxyHost=
systemProp.socksProxyPort=0
android.useAndroidX=true
android.enableJetifier=true
kotlin.compiler.execution.strategy=in-process
