import 'dart:math' as math;

import '../../../domain/word_builder_models.dart';
import '../../../word_builder_campaign_session_key.dart';

/// One unique blaster per beginner stage (1..50).
enum AngryWordsGunKind {
  peashooter,
  capPistol,
  pocketPistol,
  servicePistol,
  dualPistols,
  revolver,
  magnum,
  machinePistol,
  uzi,
  smg,
  tripleBurstSmg,
  compactShotgun,
  pumpShotgun,
  autoShotgun,
  quadBarrel,
  carbine,
  assault,
  ak47,
  battleRifle,
  burstRifle,
  lmg,
  heavySmg,
  icePistol,
  freezeRay,
  flamethrower,
  inferno,
  crossbow,
  repeatingCrossbow,
  huntingRifle,
  sniper,
  antiMateriel,
  gauss,
  laserPointer,
  pulseLaser,
  beamLaser,
  plasmaPistol,
  plasmaRifle,
  plasmaCannon,
  railgun,
  coilgun,
  grenadeLauncher,
  rpg,
  homingRocket,
  minigun,
  gatling,
  laserTank,
  tankCannon,
  twinTank,
  siege,
  doomsdayMg,
}

/// Painter / silhouette family (many guns share a body shape).
enum AngryWordsGunVisual {
  tinyPistol,
  pistol,
  dual,
  revolver,
  smg,
  shotgun,
  rifle,
  sniper,
  ice,
  flame,
  bow,
  laser,
  plasma,
  rocket,
  minigun,
  tank,
  artillery,
}

extension AngryWordsGunKindX on AngryWordsGunKind {
  AngryWordsGunVisual get visual => switch (this) {
    AngryWordsGunKind.peashooter ||
    AngryWordsGunKind.capPistol => AngryWordsGunVisual.tinyPistol,
    AngryWordsGunKind.pocketPistol ||
    AngryWordsGunKind.servicePistol => AngryWordsGunVisual.pistol,
    AngryWordsGunKind.dualPistols => AngryWordsGunVisual.dual,
    AngryWordsGunKind.revolver ||
    AngryWordsGunKind.magnum => AngryWordsGunVisual.revolver,
    AngryWordsGunKind.machinePistol ||
    AngryWordsGunKind.uzi ||
    AngryWordsGunKind.smg ||
    AngryWordsGunKind.tripleBurstSmg ||
    AngryWordsGunKind.heavySmg ||
    AngryWordsGunKind.coilgun => AngryWordsGunVisual.smg,
    AngryWordsGunKind.compactShotgun ||
    AngryWordsGunKind.pumpShotgun ||
    AngryWordsGunKind.autoShotgun ||
    AngryWordsGunKind.quadBarrel => AngryWordsGunVisual.shotgun,
    AngryWordsGunKind.carbine ||
    AngryWordsGunKind.assault ||
    AngryWordsGunKind.ak47 ||
    AngryWordsGunKind.battleRifle ||
    AngryWordsGunKind.burstRifle ||
    AngryWordsGunKind.lmg ||
    AngryWordsGunKind.gauss => AngryWordsGunVisual.rifle,
    AngryWordsGunKind.huntingRifle ||
    AngryWordsGunKind.sniper ||
    AngryWordsGunKind.antiMateriel ||
    AngryWordsGunKind.railgun => AngryWordsGunVisual.sniper,
    AngryWordsGunKind.icePistol ||
    AngryWordsGunKind.freezeRay => AngryWordsGunVisual.ice,
    AngryWordsGunKind.flamethrower ||
    AngryWordsGunKind.inferno => AngryWordsGunVisual.flame,
    AngryWordsGunKind.crossbow ||
    AngryWordsGunKind.repeatingCrossbow => AngryWordsGunVisual.bow,
    AngryWordsGunKind.laserPointer ||
    AngryWordsGunKind.pulseLaser ||
    AngryWordsGunKind.beamLaser ||
    AngryWordsGunKind.laserTank => AngryWordsGunVisual.laser,
    AngryWordsGunKind.plasmaPistol ||
    AngryWordsGunKind.plasmaRifle ||
    AngryWordsGunKind.plasmaCannon => AngryWordsGunVisual.plasma,
    AngryWordsGunKind.grenadeLauncher ||
    AngryWordsGunKind.rpg ||
    AngryWordsGunKind.homingRocket => AngryWordsGunVisual.rocket,
    AngryWordsGunKind.minigun ||
    AngryWordsGunKind.gatling ||
    AngryWordsGunKind.doomsdayMg => AngryWordsGunVisual.minigun,
    AngryWordsGunKind.tankCannon ||
    AngryWordsGunKind.twinTank => AngryWordsGunVisual.tank,
    AngryWordsGunKind.siege => AngryWordsGunVisual.artillery,
  };
}

/// Wall-ball material — HP, knockback, paint, and pop VFX.
enum AngryWordsPropMaterial {
  candy,
  plastic,
  wood,
  glass,
  water,
  rubber,
  stone,
  metal,
  ice,
  crystal,
  porcelain,
  sand,
  foam,
  magma,
  gold,
  slime,
  egg,
}

enum AngryWordsBulletElement { normal, ice, fire, plasma, laser, explosive }

class AngryWordsMaterialWeight {
  const AngryWordsMaterialWeight(this.material, this.weight);
  final AngryWordsPropMaterial material;
  final double weight;
}

/// One unique stage arsenal — beginner stage N uses index N-1.
class AngryWordsLoadout {
  const AngryWordsLoadout({
    required this.profileIndex,
    required this.label,
    required this.wallHint,
    required this.gun,
    required this.fireInterval,
    required this.bulletDamage,
    required this.pierce,
    required this.bulletRadius,
    required this.bulletSpeed,
    required this.spread,
    required this.burstChance,
    required this.pelletCount,
    required this.recoilKick,
    required this.element,
    required this.barrierCols,
    required this.barrierRows,
    required this.fillerCount,
    required this.wallMix,
    this.splashRadius = 0,
    this.homing = false,
    this.densityScale = 1,
    this.gunMounts = 1,
  });

  final int profileIndex;
  final String label;
  final String wallHint;
  final AngryWordsGunKind gun;
  final double fireInterval;
  final int bulletDamage;
  final int pierce;
  final double bulletRadius;
  final double bulletSpeed;
  final double spread;
  final double burstChance;
  final int pelletCount;
  final double recoilKick;
  final AngryWordsBulletElement element;
  final int barrierCols;
  final int barrierRows;
  final int fillerCount;
  final List<AngryWordsMaterialWeight> wallMix;
  final double splashRadius;
  final bool homing;
  final double densityScale;

  /// Side-by-side gun bodies that share aim/fire (intermediate = 2).
  /// Not the same as [pelletCount] multi-barrel on one silhouette.
  final int gunMounts;

  int get effectiveCols => (barrierCols * densityScale).round().clamp(4, 16);
  int get effectiveRows => (barrierRows * densityScale).round().clamp(3, 12);
  int get effectiveFillers => (fillerCount * densityScale).round().clamp(0, 56);

  /// Early stages stay sparse; small clutter unlocks later.
  bool get allowsSmallProps => profileIndex >= 12;

  double get earlySparseSkipChance => switch (profileIndex) {
        <= 3 => 0.48,
        <= 7 => 0.34,
        <= 11 => 0.2,
        <= 16 => 0.1,
        _ => 0.0,
      };

  /// Stages 35–36: breakable wall orbs render as emojis (pool per stage).
  bool get usesEmojiProps => emojiPropPool != null;

  List<String>? get emojiPropPool => switch (profileIndex) {
        34 => kAngryWordsStage35Emojis,
        35 => kAngryWordsStage36AnimalEmojis,
        _ => null,
      };

  /// Stage 9: cracked eggs spill yolk blobs that pool on the floor.
  bool get spillsYolk => profileIndex == 8;

  /// Fun chapter beat for UI (pacing story, not just DPS).
  String get chapterTag => switch (profileIndex) {
    <= 6 => 'Toy Box',
    <= 9 => 'Street Spray',
    <= 14 => 'Pellet Party',
    <= 21 => 'War Band',
    <= 25 => 'Ice & Fire',
    <= 31 => 'Piercers',
    <= 39 => 'Energy Age',
    <= 44 => 'Boom Brigade',
    _ => 'Endgame',
  };

  /// Campaign stage 1..50 → unique gun; difficulty densifies wall + mount count.
  static AngryWordsLoadout forSession({
    required int bookKey,
    required int levelIndex,
  }) {
    assert(
      kAngryWordsStageArsenal.length == 50,
      'Beginner arsenal must be exactly 50 unique stage guns',
    );
    final camp = decodeWordBuilderCampaignSessionKey(bookKey);
    final stage1Based = camp?.stage1Based ?? (levelIndex + 1);
    final idx = (stage1Based - 1).clamp(0, kAngryWordsStageArsenal.length - 1);
    final base = kAngryWordsStageArsenal[idx];
    final wallBoost = switch (camp?.difficulty) {
      WordBuilderDifficulty.beginner || null => 1.0,
      WordBuilderDifficulty.intermediate => 1.14,
      WordBuilderDifficulty.advanced => 1.28,
    };
    // Intermediate: two side-by-side copies of the stage gun (shared aim/fire).
    final mounts = switch (camp?.difficulty) {
      WordBuilderDifficulty.intermediate => 2,
      _ => 1,
    };
    final levelBump = 1.0 + (levelIndex.clamp(0, 8) * 0.02);
    if (wallBoost == 1.0 && levelBump == 1.0 && mounts == 1) return base;
    return base._scaled(densityScale: wallBoost * levelBump, gunMounts: mounts);
  }

  static AngryWordsLoadout forProgress(int progress) {
    final idx = progress.clamp(0, kAngryWordsStageArsenal.length - 1);
    return kAngryWordsStageArsenal[idx];
  }

  AngryWordsLoadout _scaled({
    required double densityScale,
    int? gunMounts,
  }) {
    return AngryWordsLoadout(
      profileIndex: profileIndex,
      label: label,
      wallHint: wallHint,
      gun: gun,
      fireInterval: fireInterval,
      bulletDamage: bulletDamage,
      pierce: pierce,
      bulletRadius: bulletRadius,
      bulletSpeed: bulletSpeed,
      spread: spread,
      burstChance: burstChance,
      pelletCount: pelletCount,
      recoilKick: recoilKick,
      element: element,
      barrierCols: barrierCols,
      barrierRows: barrierRows,
      fillerCount: fillerCount,
      wallMix: wallMix,
      splashRadius: splashRadius,
      homing: homing,
      densityScale: densityScale,
      gunMounts: gunMounts ?? this.gunMounts,
    );
  }

  AngryWordsPropMaterial rollMaterial(math.Random rng) {
    if (wallMix.isEmpty) return AngryWordsPropMaterial.candy;
    var total = 0.0;
    for (final w in wallMix) {
      total += w.weight;
    }
    var roll = rng.nextDouble() * total;
    for (final w in wallMix) {
      roll -= w.weight;
      if (roll <= 0) return w.material;
    }
    return wallMix.last.material;
  }

  int rollHpFor(AngryWordsPropMaterial material, math.Random rng) {
    // Stage 50: every stone cracks on 1st hit, shatters on 2nd.
    if (profileIndex == 49 && material == AngryWordsPropMaterial.stone) {
      return 2;
    }
    return switch (material) {
      AngryWordsPropMaterial.candy => rng.nextDouble() < 0.18 ? 2 : 1,
      AngryWordsPropMaterial.plastic => 1,
      AngryWordsPropMaterial.wood => rng.nextDouble() < 0.42 ? 2 : 1,
      AngryWordsPropMaterial.glass => 1,
      AngryWordsPropMaterial.water => 1,
      AngryWordsPropMaterial.rubber => 2,
      AngryWordsPropMaterial.stone => rng.nextDouble() < 0.38 ? 3 : 2,
      AngryWordsPropMaterial.metal => 3,
      AngryWordsPropMaterial.ice => 2,
      AngryWordsPropMaterial.crystal => 2,
      AngryWordsPropMaterial.porcelain => 1,
      AngryWordsPropMaterial.sand => 1,
      AngryWordsPropMaterial.foam => 1,
      AngryWordsPropMaterial.magma => 2,
      AngryWordsPropMaterial.gold => rng.nextDouble() < 0.35 ? 3 : 2,
      AngryWordsPropMaterial.slime => 2,
      AngryWordsPropMaterial.egg => 1,
    };
  }
}

const _toyCandy = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.58),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _candyPlastic = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.22),
];
const _plasticWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.32),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.2),
];
const _woodGlass = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.32),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.2),
];
const _sprayEarly = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _eggOnlyWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 1.0),
];
const _woodWater = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
];

const _woodRubber = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.28),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.38),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.porcelain, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _glassWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
];
const _rubberStone = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.28),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.36),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
];
const _stoneWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.36),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.porcelain, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
];
/// Mid/late walls stay tough via HP materials, but bias candy/plastic/egg
/// so the board reads as colorful as early toy stages (not grey metal/ice).
const _iceWater = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.16),
];
const _iceWaterDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.2),
];
const _woodIce = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.14),
];
const _woodIceDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.18),
];
const _stoneMetal = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.08),
];
const _stoneMetalDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.12),
];
const _metalStone = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalStoneHeavy = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalGlass = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalIce = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalIceDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.06),
];
const _endgame = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.06),
];
const _endgameDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.06),
];
const _fortress = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];
const _fortressDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];
const _steelCurtain = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.08),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _doomsdayWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];
/// Stage 50 keeps all-stone 2-hit rules; color comes from palette tint.
const _doomsdayMgWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 1.0),
];

/// Diverse emoji skins for stage 35 wall orbs (one per prop via RNG).
const kAngryWordsStage35Emojis = <String>[
  '🍎', '🍊', '🍋', '🍇', '🍉', '🍓', '🍑', '🍒', '🥝', '🍍',
  '🥭', '🍌', '🥥', '🍅', '🥑', '🥕', '🌽', '🍔', '🍕', '🌮',
  '🍦', '🍩', '🍪', '🎂', '🧁', '🍫', '🍬', '🍭', '🎈', '🎯',
  '⭐', '💫', '🔥', '❄️', '💎', '🎁', '🧸', '🎲', '🧩', '🎨',
  '🦄', '🐱', '🐶', '🦊', '🐼', '🐸', '🦁', '🐯', '🐨', '🐮',
  '🐷', '🐹', '🐰', '🐻', '🦉', '🦋', '🐝', '🐞', '🐢', '🐍',
  '🦖', '🦕', '🐙', '🦑', '🦀', '🐠', '🐡', '🐬', '🐳', '🦈',
  '🌵', '🌻', '🌸', '🌺', '🍄', '🌙', '☀️', '🌈', '⚡', '🍀',
  '🎸', '🎺', '🥁', '🎮', '🚀', '🛸', '⚽', '🏀', '🎾', '🏐',
];

/// Animal-only emoji skins for stage 36 wall orbs.
const kAngryWordsStage36AnimalEmojis = <String>[
  '🐶', '🐱', '🐭', '🐹', '🐰', '🦊', '🐻', '🐼', '🐻‍❄️', '🐨',
  '🐯', '🦁', '🐮', '🐷', '🐸', '🐵', '🙈', '🙉', '🙊', '🐒',
  '🐔', '🐧', '🐦', '🐤', '🐣', '🐥', '🦆', '🦅', '🦉', '🦇',
  '🐺', '🐗', '🐴', '🦄', '🐝', '🪱', '🐛', '🦋', '🐌', '🐞',
  '🐜', '🪰', '🪲', '🪳', '🦟', '🦗', '🕷️', '🦂', '🐢', '🐍',
  '🦎', '🦖', '🦕', '🐙', '🦑', '🦐', '🦞', '🦀', '🐡', '🐠',
  '🐟', '🐬', '🐳', '🐋', '🦈', '🦭', '🐊', '🐅', '🐆', '🦓',
  '🦍', '🦧', '🦣', '🐘', '🦛', '🦏', '🐪', '🐫', '🦒', '🦘',
  '🦬', '🐃', '🐂', '🐄', '🐎', '🐖', '🐏', '🐑', '🦙', '🐐',
  '🦌', '🐕', '🐩', '🦮', '🐈', '🐓', '🦃', '🦤', '🦚', '🦜',
  '🦢', '🦩', '🕊️', '🐇', '🦝', '🦨', '🦡', '🦫', '🦦', '🦥',
  '🐁', '🐀', '🐿️', '🦔',
];

/// Beginner stages 1..50 — index 0 = stage 1.
final List<AngryWordsLoadout> kAngryWordsStageArsenal = [
  // 1 Peashooter — toy single-shot, very weak
  const AngryWordsLoadout(
    profileIndex: 0,
    label: 'Peashooter',
    wallHint: 'candy · egg · foam',
    gun: AngryWordsGunKind.peashooter,
    fireInterval: 0.26,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 3.8,
    bulletSpeed: 720,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 5,
    barrierRows: 4,
    fillerCount: 2,
    wallMix: _toyCandy,
  ),
  // 2 Cap Pistol — cleaner toy click
  const AngryWordsLoadout(
    profileIndex: 1,
    label: 'Cap Pistol',
    wallHint: 'candy · plastic · egg',
    gun: AngryWordsGunKind.capPistol,
    fireInterval: 0.19,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 840,
    spread: 0.048,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.5,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 5,
    barrierRows: 4,
    fillerCount: 3,
    wallMix: _candyPlastic,
  ),
  // 3 Pocket Pistol — precise
  const AngryWordsLoadout(
    profileIndex: 2,
    label: 'Pocket Pistol',
    wallHint: 'plastic · wood · foam',
    gun: AngryWordsGunKind.pocketPistol,
    fireInterval: 0.155,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.7,
    bulletSpeed: 960,
    spread: 0.02,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.58,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 6,
    barrierRows: 4,
    fillerCount: 3,
    wallMix: _plasticWood,
  ),
  // 4 Service Pistol — firmer shot
  const AngryWordsLoadout(
    profileIndex: 3,
    label: 'Service Pistol',
    wallHint: 'plastic · wood · foam',
    gun: AngryWordsGunKind.servicePistol,
    fireInterval: 0.135,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 5.2,
    bulletSpeed: 1040,
    spread: 0.032,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.78,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 6,
    barrierRows: 5,
    fillerCount: 4,
    wallMix: _plasticWood,
  ),
  // 5 Dual Pistols — two pellets
  const AngryWordsLoadout(
    profileIndex: 4,
    label: 'Dual Pistols',
    wallHint: 'wood · glass · sand',
    gun: AngryWordsGunKind.dualPistols,
    fireInterval: 0.145,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 980,
    spread: 0.09,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 6,
    barrierRows: 5,
    fillerCount: 4,
    wallMix: _woodGlass,
  ),
  // 6 Revolver — heavy single + recoil
  const AngryWordsLoadout(
    profileIndex: 5,
    label: 'Revolver',
    wallHint: 'wood · glass · sand',
    gun: AngryWordsGunKind.revolver,
    fireInterval: 0.22,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 5.6,
    bulletSpeed: 900,
    spread: 0.038,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 1.3,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 5,
    fillerCount: 5,
    wallMix: _woodGlass,
  ),
  // 7 Magnum — chunkier than revolver
  const AngryWordsLoadout(
    profileIndex: 6,
    label: 'Magnum',
    wallHint: 'wood · glass · sand',
    gun: AngryWordsGunKind.magnum,
    fireInterval: 0.28,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 6.6,
    bulletSpeed: 880,
    spread: 0.03,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 5,
    fillerCount: 5,
    wallMix: _woodGlass,
  ),
  // 8 Machine Pistol — enter spray chapter
  const AngryWordsLoadout(
    profileIndex: 7,
    label: 'Machine Pistol',
    wallHint: 'plastic · glass · foam · bubbles',
    gun: AngryWordsGunKind.machinePistol,
    fireInterval: 0.09,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 1050,
    spread: 0.105,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.62,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 6,
    fillerCount: 6,
    wallMix: _sprayEarly,
  ),
  // 9 Uzi — egg wall; yolks spill and pool on the floor
  const AngryWordsLoadout(
    profileIndex: 8,
    label: 'Uzi',
    wallHint: 'eggs only · yolk pool',
    gun: AngryWordsGunKind.uzi,
    fireInterval: 0.068,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 1110,
    spread: 0.14,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.58,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 8,
    barrierRows: 6,
    fillerCount: 7,
    wallMix: _eggOnlyWall,
  ),
  // 10 SMG — stable professional spray
  const AngryWordsLoadout(
    profileIndex: 9,
    label: 'SMG',
    wallHint: 'wood · water · sand',
    gun: AngryWordsGunKind.smg,
    fireInterval: 0.074,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.9,
    bulletSpeed: 1160,
    spread: 0.09,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.64,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 8,
    barrierRows: 6,
    fillerCount: 8,
    wallMix: _woodWater,
  ),
  // 11 Triple Burst SMG
  const AngryWordsLoadout(
    profileIndex: 10,
    label: 'Triple Burst SMG',
    wallHint: 'wood · water · sand',
    gun: AngryWordsGunKind.tripleBurstSmg,
    fireInterval: 0.16,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.8,
    bulletSpeed: 1120,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 8,
    fillerCount: 26,
    wallMix: _woodWater,
  ),
  // 12 Compact Shotgun
  const AngryWordsLoadout(
    profileIndex: 11,
    label: 'Compact Shotgun',
    wallHint: 'glass · wood · foam',
    gun: AngryWordsGunKind.compactShotgun,
    fireInterval: 0.3,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.2,
    bulletSpeed: 820,
    spread: 0.26,
    burstChance: 0,
    pelletCount: 4,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 9,
    fillerCount: 27,
    wallMix: _glassWood,
  ),
  // 13 Pump Shotgun
  const AngryWordsLoadout(
    profileIndex: 12,
    label: 'Pump Shotgun',
    wallHint: 'glass · wood · foam',
    gun: AngryWordsGunKind.pumpShotgun,
    fireInterval: 0.28,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.4,
    bulletSpeed: 860,
    spread: 0.28,
    burstChance: 0,
    pelletCount: 5,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 9,
    fillerCount: 29,
    wallMix: _glassWood,
  ),
  // 14 Auto Shotgun
  const AngryWordsLoadout(
    profileIndex: 13,
    label: 'Auto Shotgun',
    wallHint: 'wood · rubber · porcelain',
    gun: AngryWordsGunKind.autoShotgun,
    fireInterval: 0.2,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 880,
    spread: 0.3,
    burstChance: 0.15,
    pelletCount: 5,
    recoilKick: 1.3,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 30,
    wallMix: _woodRubber,
  ),
  // 15 Quad Barrel
  const AngryWordsLoadout(
    profileIndex: 14,
    label: 'Quad Barrel',
    wallHint: 'wood · rubber · porcelain',
    gun: AngryWordsGunKind.quadBarrel,
    fireInterval: 0.32,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 840,
    spread: 0.32,
    burstChance: 0,
    pelletCount: 4,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 32,
    wallMix: _woodRubber,
  ),
  // 16 Carbine
  const AngryWordsLoadout(
    profileIndex: 15,
    label: 'Carbine',
    wallHint: 'rubber · stone · slime',
    gun: AngryWordsGunKind.carbine,
    fireInterval: 0.11,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 5.4,
    bulletSpeed: 1180,
    spread: 0.06,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.85,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 32,
    wallMix: _rubberStone,
  ),
  // 17 Assault Rifle
  const AngryWordsLoadout(
    profileIndex: 16,
    label: 'Assault Rifle',
    wallHint: 'rubber · stone · slime',
    gun: AngryWordsGunKind.assault,
    fireInterval: 0.095,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.5,
    bulletSpeed: 1200,
    spread: 0.065,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 33,
    wallMix: _rubberStone,
  ),
  // 18 AK-47
  const AngryWordsLoadout(
    profileIndex: 17,
    label: 'AK-47',
    wallHint: 'stone · wood · porcelain',
    gun: AngryWordsGunKind.ak47,
    fireInterval: 0.088,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.8,
    bulletSpeed: 1160,
    spread: 0.09,
    burstChance: 0.12,
    pelletCount: 1,
    recoilKick: 1.05,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 10,
    fillerCount: 34,
    wallMix: _stoneWood,
  ),
  // 19 Battle Rifle
  const AngryWordsLoadout(
    profileIndex: 18,
    label: 'Battle Rifle',
    wallHint: 'stone · wood · porcelain',
    gun: AngryWordsGunKind.battleRifle,
    fireInterval: 0.14,
    bulletDamage: 3,
    pierce: 1,
    bulletRadius: 5.9,
    bulletSpeed: 1240,
    spread: 0.05,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.15,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 35,
    wallMix: _stoneWood,
  ),
  // 20 Burst Rifle
  const AngryWordsLoadout(
    profileIndex: 19,
    label: 'Burst Rifle',
    wallHint: 'stone · wood · porcelain',
    gun: AngryWordsGunKind.burstRifle,
    fireInterval: 0.18,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.4,
    bulletSpeed: 1220,
    spread: 0.04,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.0,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 36,
    wallMix: _stoneWood,
  ),
  // 21 LMG
  const AngryWordsLoadout(
    profileIndex: 20,
    label: 'Light Machine Gun',
    wallHint: 'rubber · stone · slime',
    gun: AngryWordsGunKind.lmg,
    fireInterval: 0.066,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.6,
    bulletSpeed: 1180,
    spread: 0.095,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.98,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 37,
    wallMix: _rubberStone,
  ),
  // 22 Heavy SMG
  const AngryWordsLoadout(
    profileIndex: 21,
    label: 'Heavy SMG',
    wallHint: 'rubber · stone · slime',
    gun: AngryWordsGunKind.heavySmg,
    fireInterval: 0.072,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 6.8,
    bulletSpeed: 1050,
    spread: 0.125,
    burstChance: 0.08,
    pelletCount: 1,
    recoilKick: 1.08,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 39,
    wallMix: _rubberStone,
  ),
  // 23 Ice Pistol
  const AngryWordsLoadout(
    profileIndex: 22,
    label: 'Ice Pistol',
    wallHint: 'candy · egg · slime',
    gun: AngryWordsGunKind.icePistol,
    fireInterval: 0.19,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 5.5,
    bulletSpeed: 900,
    spread: 0.035,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.72,
    element: AngryWordsBulletElement.ice,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 38,
    wallMix: _iceWater,
  ),
  // 24 Freeze Ray
  const AngryWordsLoadout(
    profileIndex: 23,
    label: 'Freeze Ray',
    wallHint: 'candy · egg · slime',
    gun: AngryWordsGunKind.freezeRay,
    fireInterval: 0.11,
    bulletDamage: 1,
    pierce: 1,
    bulletRadius: 5.9,
    bulletSpeed: 1040,
    spread: 0.04,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.78,
    element: AngryWordsBulletElement.ice,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 11,
    fillerCount: 40,
    wallMix: _iceWaterDense,
  ),
  // 25 Flamethrower
  const AngryWordsLoadout(
    profileIndex: 24,
    label: 'Flamethrower',
    wallHint: 'candy · egg · slime',
    gun: AngryWordsGunKind.flamethrower,
    fireInterval: 0.092,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 6.6,
    bulletSpeed: 680,
    spread: 0.2,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.7,
    element: AngryWordsBulletElement.fire,
    splashRadius: 30,
    homing: false,
    barrierCols: 14,
    barrierRows: 11,
    fillerCount: 41,
    wallMix: _woodIce,
  ),
  // 26 Inferno Gun
  const AngryWordsLoadout(
    profileIndex: 25,
    label: 'Inferno Gun',
    wallHint: 'candy · plastic · egg',
    gun: AngryWordsGunKind.inferno,
    fireInterval: 0.07,
    bulletDamage: 1,
    pierce: 1,
    bulletRadius: 6.9,
    bulletSpeed: 760,
    spread: 0.22,
    burstChance: 0.12,
    pelletCount: 2,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.fire,
    splashRadius: 42,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 43,
    wallMix: _woodIceDense,
  ),
  // 27 Crossbow
  const AngryWordsLoadout(
    profileIndex: 26,
    label: 'Crossbow',
    wallHint: 'stone · metal · crystal',
    gun: AngryWordsGunKind.crossbow,
    fireInterval: 0.38,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1320,
    spread: 0.016,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.2,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 44,
    wallMix: _stoneMetal,
  ),
  // 28 Repeating Crossbow
  const AngryWordsLoadout(
    profileIndex: 27,
    label: 'Repeating Crossbow',
    wallHint: 'stone · metal · magma',
    gun: AngryWordsGunKind.repeatingCrossbow,
    fireInterval: 0.15,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 4.8,
    bulletSpeed: 1280,
    spread: 0.032,
    burstChance: 0.12,
    pelletCount: 1,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 45,
    wallMix: _stoneMetalDense,
  ),
  // 29 Hunting Rifle
  const AngryWordsLoadout(
    profileIndex: 28,
    label: 'Hunting Rifle',
    wallHint: 'stone · metal · magma',
    gun: AngryWordsGunKind.huntingRifle,
    fireInterval: 0.32,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1450,
    spread: 0.014,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.25,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 46,
    wallMix: _stoneMetalDense,
  ),
  // 30 Sniper Rifle
  const AngryWordsLoadout(
    profileIndex: 29,
    label: 'Sniper Rifle',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.sniper,
    fireInterval: 0.48,
    bulletDamage: 3,
    pierce: 3,
    bulletRadius: 4.5,
    bulletSpeed: 1680,
    spread: 0.008,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 48,
    wallMix: _metalStone,
  ),
  // 31 Anti-Materiel
  const AngryWordsLoadout(
    profileIndex: 30,
    label: 'Anti-Materiel Rifle',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.antiMateriel,
    fireInterval: 0.55,
    bulletDamage: 4,
    pierce: 4,
    bulletRadius: 5.4,
    bulletSpeed: 1480,
    spread: 0.006,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.75,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 50,
    wallMix: _metalStoneHeavy,
  ),
  // 32 Gauss Rifle
  const AngryWordsLoadout(
    profileIndex: 31,
    label: 'Gauss Rifle',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.gauss,
    fireInterval: 0.11,
    bulletDamage: 2,
    pierce: 3,
    bulletRadius: 4.2,
    bulletSpeed: 1880,
    spread: 0.028,
    burstChance: 0.08,
    pelletCount: 1,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 51,
    wallMix: _metalStoneHeavy,
  ),
  // 33 Laser Pointer
  const AngryWordsLoadout(
    profileIndex: 32,
    label: 'Laser Pointer',
    wallHint: 'candy · crystal · egg',
    gun: AngryWordsGunKind.laserPointer,
    fireInterval: 0.055,
    bulletDamage: 1,
    pierce: 2,
    bulletRadius: 2.6,
    bulletSpeed: 1680,
    spread: 0.004,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.32,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 52,
    wallMix: _metalGlass,
  ),
  // 34 Pulse Laser
  const AngryWordsLoadout(
    profileIndex: 33,
    label: 'Pulse Laser',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.pulseLaser,
    fireInterval: 0.048,
    bulletDamage: 1,
    pierce: 3,
    bulletRadius: 3.3,
    bulletSpeed: 1720,
    spread: 0.006,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.42,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 53,
    wallMix: _metalIce,
  ),
  // 35 Beam Laser — emoji wall (visual skin; materials still apply)
  const AngryWordsLoadout(
    profileIndex: 34,
    label: 'Beam Laser',
    wallHint: 'emoji wall · candy · gold',
    gun: AngryWordsGunKind.beamLaser,
    fireInterval: 0.034,
    bulletDamage: 2,
    pierce: 5,
    bulletRadius: 2.9,
    bulletSpeed: 1900,
    spread: 0.003,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.4,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 54,
    wallMix: _metalIceDense,
  ),
  // 36 Dual Plasma — animal emoji wall (visual skin; materials still apply)
  const AngryWordsLoadout(
    profileIndex: 35,
    label: 'Dual Plasma',
    wallHint: 'animal emoji · candy · gold',
    gun: AngryWordsGunKind.plasmaPistol,
    fireInterval: 0.125,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 6.8,
    bulletSpeed: 1080,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 0.95,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 54,
    wallMix: _metalIceDense,
  ),
  // 37 Twin Plasma Rifle
  const AngryWordsLoadout(
    profileIndex: 36,
    label: 'Twin Plasma Rifle',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.plasmaRifle,
    fireInterval: 0.085,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 7.2,
    bulletSpeed: 1180,
    spread: 0.058,
    burstChance: 0.18,
    pelletCount: 2,
    recoilKick: 1.05,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 55,
    wallMix: _endgame,
  ),
  // 38 Triple Plasma Cannon
  const AngryWordsLoadout(
    profileIndex: 37,
    label: 'Triple Plasma Cannon',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.plasmaCannon,
    fireInterval: 0.18,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 8.2,
    bulletSpeed: 980,
    spread: 0.048,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 24,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _endgameDense,
  ),
  // 39 Triple Railgun
  const AngryWordsLoadout(
    profileIndex: 38,
    label: 'Triple Railgun',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.railgun,
    fireInterval: 0.5,
    bulletDamage: 4,
    pierce: 4,
    bulletRadius: 4.2,
    bulletSpeed: 2050,
    spread: 0.018,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.85,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _metalStoneHeavy,
  ),
  // 40 Triple Coilgun
  const AngryWordsLoadout(
    profileIndex: 39,
    label: 'Triple Coilgun',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.coilgun,
    fireInterval: 0.05,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1580,
    spread: 0.085,
    burstChance: 0.2,
    pelletCount: 3,
    recoilKick: 0.85,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _metalStoneHeavy,
  ),
  // 41 Grenade Launcher
  const AngryWordsLoadout(
    profileIndex: 40,
    label: 'Grenade Launcher',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.grenadeLauncher,
    fireInterval: 0.36,
    bulletDamage: 3,
    pierce: 0,
    bulletRadius: 7.8,
    bulletSpeed: 740,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 44,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _fortress,
  ),
  // 42 RPG
  const AngryWordsLoadout(
    profileIndex: 41,
    label: 'RPG',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.rpg,
    fireInterval: 0.52,
    bulletDamage: 5,
    pierce: 0,
    bulletRadius: 8.8,
    bulletSpeed: 700,
    spread: 0.035,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.85,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 56,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _fortressDense,
  ),
  // 43 Homing Rocket
  const AngryWordsLoadout(
    profileIndex: 42,
    label: 'Homing Rocket',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.homingRocket,
    fireInterval: 0.46,
    bulletDamage: 4,
    pierce: 0,
    bulletRadius: 8.0,
    bulletSpeed: 660,
    spread: 0.06,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.6,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 52,
    homing: true,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _fortressDense,
  ),
  // 44 Mini-Gun
  const AngryWordsLoadout(
    profileIndex: 43,
    label: 'Mini-Gun',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.minigun,
    fireInterval: 0.034,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.0,
    bulletSpeed: 1340,
    spread: 0.145,
    burstChance: 0.18,
    pelletCount: 1,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _steelCurtain,
  ),
  // 45 Gatling
  const AngryWordsLoadout(
    profileIndex: 44,
    label: 'Gatling',
    wallHint: 'candy · gold · egg',
    gun: AngryWordsGunKind.gatling,
    fireInterval: 0.028,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 5.4,
    bulletSpeed: 1400,
    spread: 0.11,
    burstChance: 0.2,
    pelletCount: 1,
    recoilKick: 0.98,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _steelCurtain,
  ),
  // 46 Laser Tank Turret
  const AngryWordsLoadout(
    profileIndex: 45,
    label: 'Laser Tank Turret',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.laserTank,
    fireInterval: 0.036,
    bulletDamage: 2,
    pierce: 5,
    bulletRadius: 3.2,
    bulletSpeed: 1850,
    spread: 0.004,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.5,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _endgameDense,
  ),
  // 47 Hybrid Tank — hold-to-spray dual: laser + explosive
  const AngryWordsLoadout(
    profileIndex: 46,
    label: 'Hybrid Tank',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.tankCannon,
    fireInterval: 0.1,
    bulletDamage: 4,
    pierce: 0,
    bulletRadius: 9.2,
    bulletSpeed: 1020,
    spread: 0.055,
    burstChance: 0.12,
    pelletCount: 2,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 42,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _endgameDense,
  ),
  // 48 Twin Tank Guns
  const AngryWordsLoadout(
    profileIndex: 47,
    label: 'Twin Tank Guns',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.twinTank,
    fireInterval: 0.4,
    bulletDamage: 3,
    pierce: 0,
    bulletRadius: 8.4,
    bulletSpeed: 900,
    spread: 0.08,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 1.8,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 46,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _doomsdayWall,
  ),
  // 49 Siege Artillery — triple barrel
  const AngryWordsLoadout(
    profileIndex: 48,
    label: 'Siege Artillery',
    wallHint: 'candy · magma · gold',
    gun: AngryWordsGunKind.siege,
    fireInterval: 0.66,
    bulletDamage: 5,
    pierce: 0,
    bulletRadius: 9.2,
    bulletSpeed: 720,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 2.1,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 66,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _doomsdayWall,
  ),
  // 50 Doomsday MG — 5-barrel chaingun vs all-stone wall (2-hit crack→shatter)
  const AngryWordsLoadout(
    profileIndex: 49,
    label: 'Doomsday MG',
    wallHint: 'all stone · 2-hit',
    gun: AngryWordsGunKind.doomsdayMg,
    fireInterval: 0.03,
    bulletDamage: 1,
    pierce: 3,
    bulletRadius: 6.0,
    bulletSpeed: 1480,
    spread: 0.1,
    burstChance: 0.18,
    pelletCount: 5,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    wallMix: _doomsdayMgWall,
  ),
];
