import 'dart:math' as math;

import '../../../data/prop_archetypes/wb_prop_archetype.dart';
import '../../../domain/word_builder_models.dart';
import '../../../word_builder_campaign_session_key.dart';

/// One unique blaster per beginner stage (1..50).
enum AngryWordsGunKind {
  peashooter,
  capPistol,
  pocketPistol,
  servicePistol,
  dualPistols,
  revolver,
  magnum,
  machinePistol,
  uzi,
  smg,
  tripleBurstSmg,
  compactShotgun,
  pumpShotgun,
  autoShotgun,
  quadBarrel,
  carbine,
  assault,
  ak47,
  battleRifle,
  burstRifle,
  lmg,
  heavySmg,
  icePistol,
  freezeRay,
  flamethrower,
  inferno,
  crossbow,
  repeatingCrossbow,
  huntingRifle,
  sniper,
  antiMateriel,
  gauss,
  laserPointer,
  pulseLaser,
  beamLaser,
  plasmaPistol,
  plasmaRifle,
  plasmaCannon,
  railgun,
  coilgun,
  grenadeLauncher,
  rpg,
  homingRocket,
  minigun,
  gatling,
  laserTank,
  tankCannon,
  twinTank,
  siege,
  doomsdayMg,
}

/// Painter / silhouette family (many guns share a body shape).
enum AngryWordsGunVisual {
  tinyPistol,
  pistol,
  dual,
  revolver,
  smg,
  shotgun,
  rifle,
  sniper,
  ice,
  flame,
  bow,
  laser,
  plasma,
  rocket,
  minigun,
  tank,
  artillery,
}

extension AngryWordsGunKindX on AngryWordsGunKind {
  AngryWordsGunVisual get visual => switch (this) {
    AngryWordsGunKind.peashooter ||
    AngryWordsGunKind.capPistol => AngryWordsGunVisual.tinyPistol,
    AngryWordsGunKind.pocketPistol ||
    AngryWordsGunKind.servicePistol => AngryWordsGunVisual.pistol,
    AngryWordsGunKind.dualPistols => AngryWordsGunVisual.dual,
    AngryWordsGunKind.revolver ||
    AngryWordsGunKind.magnum => AngryWordsGunVisual.revolver,
    AngryWordsGunKind.machinePistol ||
    AngryWordsGunKind.uzi ||
    AngryWordsGunKind.smg ||
    AngryWordsGunKind.tripleBurstSmg ||
    AngryWordsGunKind.heavySmg ||
    AngryWordsGunKind.coilgun => AngryWordsGunVisual.smg,
    AngryWordsGunKind.compactShotgun ||
    AngryWordsGunKind.pumpShotgun ||
    AngryWordsGunKind.autoShotgun ||
    AngryWordsGunKind.quadBarrel => AngryWordsGunVisual.shotgun,
    AngryWordsGunKind.carbine ||
    AngryWordsGunKind.assault ||
    AngryWordsGunKind.ak47 ||
    AngryWordsGunKind.battleRifle ||
    AngryWordsGunKind.burstRifle ||
    AngryWordsGunKind.lmg ||
    AngryWordsGunKind.gauss => AngryWordsGunVisual.rifle,
    AngryWordsGunKind.huntingRifle ||
    AngryWordsGunKind.sniper ||
    AngryWordsGunKind.antiMateriel ||
    AngryWordsGunKind.railgun => AngryWordsGunVisual.sniper,
    AngryWordsGunKind.icePistol ||
    AngryWordsGunKind.freezeRay => AngryWordsGunVisual.ice,
    AngryWordsGunKind.flamethrower ||
    AngryWordsGunKind.inferno => AngryWordsGunVisual.flame,
    AngryWordsGunKind.crossbow ||
    AngryWordsGunKind.repeatingCrossbow => AngryWordsGunVisual.bow,
    AngryWordsGunKind.laserPointer ||
    AngryWordsGunKind.pulseLaser ||
    AngryWordsGunKind.beamLaser ||
    AngryWordsGunKind.laserTank => AngryWordsGunVisual.laser,
    AngryWordsGunKind.plasmaPistol ||
    AngryWordsGunKind.plasmaRifle ||
    AngryWordsGunKind.plasmaCannon => AngryWordsGunVisual.plasma,
    AngryWordsGunKind.grenadeLauncher ||
    AngryWordsGunKind.rpg ||
    AngryWordsGunKind.homingRocket => AngryWordsGunVisual.rocket,
    AngryWordsGunKind.minigun ||
    AngryWordsGunKind.gatling ||
    AngryWordsGunKind.doomsdayMg => AngryWordsGunVisual.minigun,
    AngryWordsGunKind.tankCannon ||
    AngryWordsGunKind.twinTank => AngryWordsGunVisual.tank,
    AngryWordsGunKind.siege => AngryWordsGunVisual.artillery,
  };
}

/// Wall-ball material — HP, knockback, paint, and pop VFX.
enum AngryWordsPropMaterial {
  candy,
  plastic,
  wood,
  glass,
  water,
  rubber,
  stone,
  metal,
  ice,
  crystal,
  porcelain,
  sand,
  foam,
  magma,
  gold,
  slime,
  egg,
}

enum AngryWordsBulletElement { normal, ice, fire, plasma, laser, explosive }

class AngryWordsMaterialWeight {
  const AngryWordsMaterialWeight(this.material, this.weight);
  final AngryWordsPropMaterial material;
  final double weight;
}

/// One unique stage arsenal — beginner stage N uses index N-1.
class AngryWordsLoadout {
  const AngryWordsLoadout({
    required this.profileIndex,
    required this.label,
    required this.gun,
    required this.fireInterval,
    required this.bulletDamage,
    required this.pierce,
    required this.bulletRadius,
    required this.bulletSpeed,
    required this.spread,
    required this.burstChance,
    required this.pelletCount,
    required this.recoilKick,
    required this.element,
    required this.barrierCols,
    required this.barrierRows,
    required this.fillerCount,
    required this.wallMix,
    required this.primaryArchetype,
    this.fillerArchetype,
    this.primaryRatio = 0.7,
    this.usesHammer = false,
    this.splashRadius = 0,
    this.homing = false,
    this.densityScale = 1,
    this.gunMounts = 1,
  });

  final int profileIndex;
  final String label;
  final AngryWordsGunKind gun;
  final double fireInterval;
  final int bulletDamage;
  final int pierce;
  final double bulletRadius;
  final double bulletSpeed;
  final double spread;
  final double burstChance;
  final int pelletCount;
  final double recoilKick;
  final AngryWordsBulletElement element;
  final int barrierCols;
  final int barrierRows;
  final int fillerCount;

  /// Kept for elemental weak spots / [rollHpFor] — prop skins use archetypes.
  final List<AngryWordsMaterialWeight> wallMix;

  /// Cargo / majority wall identity (~[primaryRatio]).
  final WbPropArchetype primaryArchetype;

  /// Same-chapter filler skin; `null` = pure primary wall (locked stages).
  final WbPropArchetype? fillerArchetype;

  /// Share of props that use [primaryArchetype] (rest use filler).
  final double primaryRatio;

  /// Design flag: stage tip uses hammer (not derived from wall type).
  final bool usesHammer;

  final double splashRadius;
  final bool homing;
  final double densityScale;

  /// Side-by-side gun bodies that share aim/fire (intermediate = 2).
  /// Not the same as [pelletCount] multi-barrel on one silhouette.
  final int gunMounts;

  /// UI chip from archetype labels (e.g. `کوزه سفالی · ماسه‌سنگ`).
  String get wallHint {
    final primary = kWbArchetypes[primaryArchetype];
    final pLabel = primary?.labelFa ?? label;
    final fillerId = fillerArchetype;
    if (fillerId == null) return pLabel;
    final filler = kWbArchetypes[fillerId];
    if (filler == null) return pLabel;
    return '$pLabel · ${filler.labelFa}';
  }

  static const int kMaxBarrierCols = 9;
  static const int kMaxBarrierRows = 6;
  static const int kMaxBarrierFillers = 12;

  /// Soft ceiling for total cage orbs (grid + fillers). Full board, not crushed.
  static const int kMaxCageProps = 50;

  /// Dense themed walls pack past the default soft ceiling.
  int get maxCageProps => switch (profileIndex) {
    3 => 62, // stage 4 soda cans
    39 => 78, // stage 40 oil-barrel sea
    _ => kMaxCageProps,
  };

  int get effectiveCols {
    final cap = profileIndex == 39 ? 12 : kMaxBarrierCols;
    return (barrierCols * densityScale).round().clamp(4, cap);
  }

  int get effectiveRows {
    final cap = profileIndex == 39 ? 8 : kMaxBarrierRows;
    return (barrierRows * densityScale).round().clamp(3, cap);
  }

  /// Arsenal lists climb to 56 fillers — plateau so late stages stay playable.
  int get effectiveFillers {
    final scaled = (fillerCount * densityScale).round();
    final plateaued = switch (scaled) {
      <= 8 => scaled,
      <= 24 => 8 + ((scaled - 8) * 0.28).round(),
      _ => 12 + ((scaled - 24) * 0.08).round(),
    };
    return plateaued.clamp(0, kMaxBarrierFillers);
  }

  /// Early stages stay sparse; small clutter unlocks later.
  bool get allowsSmallProps => profileIndex >= 12;

  /// Always leave a little air — never pack the grid 100%.
  /// Stage 4 (soda cans) and stage 40 (oil barrels) are intentionally dense.
  double get earlySparseSkipChance => switch (profileIndex) {
    3 => 0.05,
    39 => 0.03,
    <= 2 => 0.48,
    <= 7 => 0.34,
    <= 11 => 0.22,
    <= 19 => 0.14,
    <= 29 => 0.09,
    _ => 0.06,
  };

  /// Stages 35–36: breakable wall orbs render as emojis (pool per stage).
  bool get usesEmojiProps => emojiPropPool != null;

  List<String>? get emojiPropPool => switch (profileIndex) {
    34 => kAngryWordsStage35Emojis,
    35 => kAngryWordsStage36AnimalEmojis,
    _ => null,
  };

  /// Stage 9 / egg primary: cracked eggs spill yolk blobs that pool on the floor.
  bool get spillsYolk =>
      profileIndex == 8 || primaryArchetype == WbPropArchetype.egg;

  /// Fun chapter beat for UI (pacing story, not just DPS).
  String get chapterTag => switch (profileIndex) {
    <= 6 => 'Toy Box',
    <= 9 => 'Street Spray',
    <= 14 => 'Pellet Party',
    <= 21 => 'War Band',
    <= 25 => 'Ice & Fire',
    <= 31 => 'Piercers',
    <= 39 => 'Energy Age',
    <= 44 => 'Boom Brigade',
    _ => 'Endgame',
  };

  /// Pick primary vs filler for a wall prop (cargo letters use primary).
  WbPropArchetype rollArchetype(math.Random rng) {
    final filler = fillerArchetype;
    if (filler == null) return primaryArchetype;
    if (rng.nextDouble() < primaryRatio.clamp(0.0, 1.0)) {
      return primaryArchetype;
    }
    return filler;
  }

  int hpForArchetype(WbPropArchetype id, math.Random rng) {
    final spec = kWbArchetypes[id];
    if (spec == null) return rollHpFor(AngryWordsPropMaterial.candy, rng);
    if (spec.hpOverride > 0) return spec.hpOverride;
    return rollHpFor(spec.material, rng);
  }

  /// Campaign stage 1..50 → unique gun; difficulty densifies wall + mount count.
  static AngryWordsLoadout forSession({
    required int bookKey,
    required int levelIndex,
  }) {
    assert(
      kAngryWordsStageArsenal.length == 50,
      'Beginner arsenal must be exactly 50 unique stage guns',
    );
    final camp = decodeWordBuilderCampaignSessionKey(bookKey);
    final stage1Based = camp?.stage1Based ?? (levelIndex + 1);
    final idx = (stage1Based - 1).clamp(0, kAngryWordsStageArsenal.length - 1);
    final base = kAngryWordsStageArsenal[idx];
    final wallBoost = switch (camp?.difficulty) {
      WordBuilderDifficulty.beginner || null => 1.0,
      WordBuilderDifficulty.intermediate => 1.14,
      WordBuilderDifficulty.advanced => 1.28,
    };
    // Intermediate: two side-by-side copies of the stage gun (shared aim/fire).
    final mounts = switch (camp?.difficulty) {
      WordBuilderDifficulty.intermediate => 2,
      _ => 1,
    };
    final levelBump = 1.0 + (levelIndex.clamp(0, 8) * 0.02);
    if (wallBoost == 1.0 && levelBump == 1.0 && mounts == 1) return base;
    return base._scaled(densityScale: wallBoost * levelBump, gunMounts: mounts);
  }

  static AngryWordsLoadout forProgress(int progress) {
    final idx = progress.clamp(0, kAngryWordsStageArsenal.length - 1);
    return kAngryWordsStageArsenal[idx];
  }

  AngryWordsLoadout _scaled({required double densityScale, int? gunMounts}) {
    return AngryWordsLoadout(
      profileIndex: profileIndex,
      label: label,
      gun: gun,
      fireInterval: fireInterval,
      bulletDamage: bulletDamage,
      pierce: pierce,
      bulletRadius: bulletRadius,
      bulletSpeed: bulletSpeed,
      spread: spread,
      burstChance: burstChance,
      pelletCount: pelletCount,
      recoilKick: recoilKick,
      element: element,
      barrierCols: barrierCols,
      barrierRows: barrierRows,
      fillerCount: fillerCount,
      wallMix: wallMix,
      primaryArchetype: primaryArchetype,
      fillerArchetype: fillerArchetype,
      primaryRatio: primaryRatio,
      usesHammer: usesHammer,
      splashRadius: splashRadius,
      homing: homing,
      densityScale: densityScale,
      gunMounts: gunMounts ?? this.gunMounts,
    );
  }

  AngryWordsPropMaterial rollMaterial(math.Random rng) {
    if (wallMix.isEmpty) return AngryWordsPropMaterial.candy;
    var total = 0.0;
    for (final w in wallMix) {
      total += w.weight;
    }
    var roll = rng.nextDouble() * total;
    for (final w in wallMix) {
      roll -= w.weight;
      if (roll <= 0) return w.material;
    }
    return wallMix.last.material;
  }

  int rollHpFor(AngryWordsPropMaterial material, math.Random rng) {
    // Stage 50: every stone cracks on 1st hit, shatters on 2nd.
    if (profileIndex == 49 && material == AngryWordsPropMaterial.stone) {
      return 2;
    }
    return switch (material) {
      AngryWordsPropMaterial.candy => rng.nextDouble() < 0.18 ? 2 : 1,
      AngryWordsPropMaterial.plastic => 1,
      AngryWordsPropMaterial.wood => rng.nextDouble() < 0.42 ? 2 : 1,
      AngryWordsPropMaterial.glass => 1,
      AngryWordsPropMaterial.water => 1,
      AngryWordsPropMaterial.rubber => 2,
      AngryWordsPropMaterial.stone => rng.nextDouble() < 0.38 ? 3 : 2,
      AngryWordsPropMaterial.metal => 3,
      AngryWordsPropMaterial.ice => 2,
      AngryWordsPropMaterial.crystal => 2,
      AngryWordsPropMaterial.porcelain => 1,
      AngryWordsPropMaterial.sand => 1,
      AngryWordsPropMaterial.foam => 1,
      AngryWordsPropMaterial.magma => 2,
      AngryWordsPropMaterial.gold => rng.nextDouble() < 0.35 ? 3 : 2,
      AngryWordsPropMaterial.slime => 2,
      AngryWordsPropMaterial.egg => 1,
    };
  }
}

const _toyCandy = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.58),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _candyPlastic = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.22),
];
const _plasticWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.32),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.2),
];
const _woodGlass = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.34),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.32),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.2),
];
const _sprayEarly = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _eggOnlyWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 1.0),
];
const _woodWater = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.sand, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
];

const _woodRubber = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.28),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.38),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.porcelain, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.18),
];
const _glassWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
];
const _rubberStone = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.28),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.36),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
];
const _stoneWood = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.36),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.3),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.porcelain, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
];

/// Mid/late walls stay tough via HP materials, but bias candy/plastic/egg
/// so the board reads as colorful as early toy stages (not grey metal/ice).
const _iceWater = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.26),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.water, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.16),
];
const _iceWaterDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.2),
];
const _woodIce = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.14),
];
const _woodIceDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.wood, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.18),
];
const _stoneMetal = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.24),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.08),
];
const _stoneMetalDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.12),
];
const _metalStone = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalStoneHeavy = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalGlass = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.glass, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.foam, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalIce = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.22),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _metalIceDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.ice, 0.06),
];
const _endgame = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.06),
];
const _endgameDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.06),
];
const _fortress = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];
const _fortressDense = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];
const _steelCurtain = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.2),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.16),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.crystal, 0.08),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.metal, 0.04),
];
const _doomsdayWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.candy, 0.18),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.plastic, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.egg, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.magma, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.gold, 0.14),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.slime, 0.12),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.rubber, 0.1),
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 0.04),
];

/// Stage 50 keeps all-stone 2-hit rules; color comes from palette tint.
const _doomsdayMgWall = [
  AngryWordsMaterialWeight(AngryWordsPropMaterial.stone, 1.0),
];

/// Diverse emoji skins for stage 35 wall orbs (one per prop via RNG).
const kAngryWordsStage35Emojis = <String>[
  '🍎',
  '🍊',
  '🍋',
  '🍇',
  '🍉',
  '🍓',
  '🍑',
  '🍒',
  '🥝',
  '🍍',
  '🥭',
  '🍌',
  '🥥',
  '🍅',
  '🥑',
  '🥕',
  '🌽',
  '🍔',
  '🍕',
  '🌮',
  '🍦',
  '🍩',
  '🍪',
  '🎂',
  '🧁',
  '🍫',
  '🍬',
  '🍭',
  '🎈',
  '🎯',
  '⭐',
  '💫',
  '🔥',
  '❄️',
  '💎',
  '🎁',
  '🧸',
  '🎲',
  '🧩',
  '🎨',
  '🦄',
  '🐱',
  '🐶',
  '🦊',
  '🐼',
  '🐸',
  '🦁',
  '🐯',
  '🐨',
  '🐮',
  '🐷',
  '🐹',
  '🐰',
  '🐻',
  '🦉',
  '🦋',
  '🐝',
  '🐞',
  '🐢',
  '🐍',
  '🦖',
  '🦕',
  '🐙',
  '🦑',
  '🦀',
  '🐠',
  '🐡',
  '🐬',
  '🐳',
  '🦈',
  '🌵',
  '🌻',
  '🌸',
  '🌺',
  '🍄',
  '🌙',
  '☀️',
  '🌈',
  '⚡',
  '🍀',
  '🎸',
  '🎺',
  '🥁',
  '🎮',
  '🚀',
  '🛸',
  '⚽',
  '🏀',
  '🎾',
  '🏐',
];

/// Animal-only emoji skins for stage 36 wall orbs.
const kAngryWordsStage36AnimalEmojis = <String>[
  '🐶',
  '🐱',
  '🐭',
  '🐹',
  '🐰',
  '🦊',
  '🐻',
  '🐼',
  '🐻‍❄️',
  '🐨',
  '🐯',
  '🦁',
  '🐮',
  '🐷',
  '🐸',
  '🐵',
  '🙈',
  '🙉',
  '🙊',
  '🐒',
  '🐔',
  '🐧',
  '🐦',
  '🐤',
  '🐣',
  '🐥',
  '🦆',
  '🦅',
  '🦉',
  '🦇',
  '🐺',
  '🐗',
  '🐴',
  '🦄',
  '🐝',
  '🪱',
  '🐛',
  '🦋',
  '🐌',
  '🐞',
  '🐜',
  '🪰',
  '🪲',
  '🪳',
  '🦟',
  '🦗',
  '🕷️',
  '🦂',
  '🐢',
  '🐍',
  '🦎',
  '🦖',
  '🦕',
  '🐙',
  '🦑',
  '🦐',
  '🦞',
  '🦀',
  '🐡',
  '🐠',
  '🐟',
  '🐬',
  '🐳',
  '🐋',
  '🦈',
  '🦭',
  '🐊',
  '🐅',
  '🐆',
  '🦓',
  '🦍',
  '🦧',
  '🦣',
  '🐘',
  '🦛',
  '🦏',
  '🐪',
  '🐫',
  '🦒',
  '🦘',
  '🦬',
  '🐃',
  '🐂',
  '🐄',
  '🐎',
  '🐖',
  '🐏',
  '🐑',
  '🦙',
  '🐐',
  '🦌',
  '🐕',
  '🐩',
  '🦮',
  '🐈',
  '🐓',
  '🦃',
  '🦤',
  '🦚',
  '🦜',
  '🦢',
  '🦩',
  '🕊️',
  '🐇',
  '🦝',
  '🦨',
  '🦡',
  '🦫',
  '🦦',
  '🦥',
  '🐁',
  '🐀',
  '🐿️',
  '🦔',
];

/// Beginner stages 1..50 — index 0 = stage 1.
final List<AngryWordsLoadout> kAngryWordsStageArsenal = [
  // 1 Peashooter — toy single-shot, very weak
  const AngryWordsLoadout(
    profileIndex: 0,
    label: 'Peashooter',
    gun: AngryWordsGunKind.peashooter,
    fireInterval: 0.26,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 3.8,
    bulletSpeed: 720,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 5,
    barrierRows: 4,
    fillerCount: 2,
    primaryArchetype: WbPropArchetype.balloon,
    fillerArchetype: WbPropArchetype.candyBall,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _toyCandy,
  ),
  // 2 Cap Pistol — pure candy wall (🍬 look + bounce)
  const AngryWordsLoadout(
    profileIndex: 1,
    label: 'Cap Pistol',
    gun: AngryWordsGunKind.capPistol,
    fireInterval: 0.19,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 840,
    spread: 0.048,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.5,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 5,
    barrierRows: 4,
    fillerCount: 3,
    primaryArchetype: WbPropArchetype.candyBall,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _candyPlastic,
  ),
  // 3 Pocket Pistol — pure balloon wall (🎈 look + helium float)
  const AngryWordsLoadout(
    profileIndex: 2,
    label: 'Pocket Pistol',
    gun: AngryWordsGunKind.pocketPistol,
    fireInterval: 0.155,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.7,
    bulletSpeed: 960,
    spread: 0.02,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.58,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 6,
    barrierRows: 4,
    fillerCount: 3,
    primaryArchetype: WbPropArchetype.balloon,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _toyCandy,
  ),
  // 4 Service Pistol — dense soda-can wall (assets/items/can.png)
  const AngryWordsLoadout(
    profileIndex: 3,
    label: 'Service Pistol',
    gun: AngryWordsGunKind.servicePistol,
    fireInterval: 0.135,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 5.2,
    bulletSpeed: 1040,
    spread: 0.032,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.78,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 9,
    barrierRows: 6,
    fillerCount: 12,
    primaryArchetype: WbPropArchetype.sodaCan,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _plasticWood,
  ),
  // 5 Dual Pistols — pure oil-barrel wall (assets/items/oilbarrel.png)
  const AngryWordsLoadout(
    profileIndex: 4,
    label: 'Dual Pistols',
    gun: AngryWordsGunKind.dualPistols,
    fireInterval: 0.145,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 980,
    spread: 0.09,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 5,
    fillerCount: 6,
    primaryArchetype: WbPropArchetype.oilDrum,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodGlass,
  ),
  // 6 Revolver — stage-6 lamp wall, first-hit damaged sprite + split fragments.
  const AngryWordsLoadout(
    profileIndex: 5,
    label: 'Revolver',
    gun: AngryWordsGunKind.revolver,
    fireInterval: 0.22,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 5.6,
    bulletSpeed: 900,
    spread: 0.038,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 1.3,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 8,
    barrierRows: 6,
    fillerCount: 8,
    primaryArchetype: WbPropArchetype.oilLamp,
    fillerArchetype: WbPropArchetype.oilLamp,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodGlass,
  ),
  // 7 Magnum — chunkier than revolver
  const AngryWordsLoadout(
    profileIndex: 6,
    label: 'Magnum',
    gun: AngryWordsGunKind.magnum,
    fireInterval: 0.28,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 6.6,
    bulletSpeed: 880,
    spread: 0.03,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 5,
    fillerCount: 5,
    primaryArchetype: WbPropArchetype.piggyBank,
    fillerArchetype: WbPropArchetype.candyBall,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodGlass,
  ),
  // 8 Machine Pistol — enter spray chapter
  const AngryWordsLoadout(
    profileIndex: 7,
    label: 'Machine Pistol',
    gun: AngryWordsGunKind.machinePistol,
    fireInterval: 0.09,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 1050,
    spread: 0.105,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.62,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 7,
    barrierRows: 6,
    fillerCount: 6,
    primaryArchetype: WbPropArchetype.sodaCan,
    fillerArchetype: WbPropArchetype.sprayCan,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _sprayEarly,
  ),
  // 9 Uzi — egg wall; yolks spill and pool on the floor
  const AngryWordsLoadout(
    profileIndex: 8,
    label: 'Uzi',
    gun: AngryWordsGunKind.uzi,
    fireInterval: 0.068,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 1110,
    spread: 0.14,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.58,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 8,
    barrierRows: 6,
    fillerCount: 7,
    primaryArchetype: WbPropArchetype.egg,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _eggOnlyWall,
  ),
  // 10 SMG — stable professional spray
  const AngryWordsLoadout(
    profileIndex: 9,
    label: 'SMG',
    gun: AngryWordsGunKind.smg,
    fireInterval: 0.074,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.9,
    bulletSpeed: 1160,
    spread: 0.09,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.64,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 8,
    barrierRows: 6,
    fillerCount: 8,
    primaryArchetype: WbPropArchetype.oilDrum,
    fillerArchetype: WbPropArchetype.sodaCan,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodWater,
  ),
  // 11 Triple Burst SMG
  const AngryWordsLoadout(
    profileIndex: 10,
    label: 'Triple Burst SMG',
    gun: AngryWordsGunKind.tripleBurstSmg,
    fireInterval: 0.16,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.8,
    bulletSpeed: 1120,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 8,
    fillerCount: 26,
    primaryArchetype: WbPropArchetype.pinata,
    fillerArchetype: WbPropArchetype.confettiBall,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodWater,
  ),
  // 12 Compact Shotgun
  const AngryWordsLoadout(
    profileIndex: 11,
    label: 'Compact Shotgun',
    gun: AngryWordsGunKind.compactShotgun,
    fireInterval: 0.3,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.2,
    bulletSpeed: 820,
    spread: 0.26,
    burstChance: 0,
    pelletCount: 4,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 9,
    fillerCount: 27,
    primaryArchetype: WbPropArchetype.watermelon,
    fillerArchetype: WbPropArchetype.soapBubble,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _glassWood,
  ),
  // 13 Pump Shotgun
  const AngryWordsLoadout(
    profileIndex: 12,
    label: 'Pump Shotgun',
    gun: AngryWordsGunKind.pumpShotgun,
    fireInterval: 0.28,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.4,
    bulletSpeed: 860,
    spread: 0.28,
    burstChance: 0,
    pelletCount: 5,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 12,
    barrierRows: 9,
    fillerCount: 29,
    primaryArchetype: WbPropArchetype.soapBubble,
    fillerArchetype: WbPropArchetype.confettiBall,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _glassWood,
  ),
  // 14 Auto Shotgun
  const AngryWordsLoadout(
    profileIndex: 13,
    label: 'Auto Shotgun',
    gun: AngryWordsGunKind.autoShotgun,
    fireInterval: 0.2,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.5,
    bulletSpeed: 880,
    spread: 0.3,
    burstChance: 0.15,
    pelletCount: 5,
    recoilKick: 1.3,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 30,
    primaryArchetype: WbPropArchetype.discoBall,
    fillerArchetype: WbPropArchetype.sodaCan,
    primaryRatio: 0.6,
    usesHammer: false,
    wallMix: _woodRubber,
  ),
  // 15 Quad Barrel
  const AngryWordsLoadout(
    profileIndex: 14,
    label: 'Quad Barrel',
    gun: AngryWordsGunKind.quadBarrel,
    fireInterval: 0.32,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 4.6,
    bulletSpeed: 840,
    spread: 0.32,
    burstChance: 0,
    pelletCount: 4,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 32,
    primaryArchetype: WbPropArchetype.confettiBall,
    fillerArchetype: WbPropArchetype.soapBubble,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodRubber,
  ),
  // 16 Carbine
  const AngryWordsLoadout(
    profileIndex: 15,
    label: 'Carbine',
    gun: AngryWordsGunKind.carbine,
    fireInterval: 0.11,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 5.4,
    bulletSpeed: 1180,
    spread: 0.06,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.85,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 32,
    primaryArchetype: WbPropArchetype.woodBarrel,
    fillerArchetype: WbPropArchetype.woodTarget,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _rubberStone,
  ),
  // 17 Assault Rifle
  const AngryWordsLoadout(
    profileIndex: 16,
    label: 'Assault Rifle',
    gun: AngryWordsGunKind.assault,
    fireInterval: 0.095,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.5,
    bulletSpeed: 1200,
    spread: 0.065,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 9,
    fillerCount: 33,
    primaryArchetype: WbPropArchetype.brick,
    fillerArchetype: WbPropArchetype.sandstone,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _rubberStone,
  ),
  // 18 AK-47
  const AngryWordsLoadout(
    profileIndex: 17,
    label: 'AK-47',
    gun: AngryWordsGunKind.ak47,
    fireInterval: 0.088,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.8,
    bulletSpeed: 1160,
    spread: 0.09,
    burstChance: 0.12,
    pelletCount: 1,
    recoilKick: 1.05,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 13,
    barrierRows: 10,
    fillerCount: 34,
    primaryArchetype: WbPropArchetype.tinCan,
    fillerArchetype: WbPropArchetype.oilDrum,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneWood,
  ),
  // 19 Battle Rifle
  const AngryWordsLoadout(
    profileIndex: 18,
    label: 'Battle Rifle',
    gun: AngryWordsGunKind.battleRifle,
    fireInterval: 0.14,
    bulletDamage: 3,
    pierce: 1,
    bulletRadius: 5.9,
    bulletSpeed: 1240,
    spread: 0.05,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.15,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 35,
    primaryArchetype: WbPropArchetype.oilDrum,
    fillerArchetype: WbPropArchetype.tinCan,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneWood,
  ),
  // 20 Burst Rifle
  const AngryWordsLoadout(
    profileIndex: 19,
    label: 'Burst Rifle',
    gun: AngryWordsGunKind.burstRifle,
    fireInterval: 0.18,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.4,
    bulletSpeed: 1220,
    spread: 0.04,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.0,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 36,
    primaryArchetype: WbPropArchetype.sandstone,
    fillerArchetype: WbPropArchetype.brick,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneWood,
  ),
  // 21 LMG
  const AngryWordsLoadout(
    profileIndex: 20,
    label: 'Light Machine Gun',
    gun: AngryWordsGunKind.lmg,
    fireInterval: 0.066,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.6,
    bulletSpeed: 1180,
    spread: 0.095,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.98,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 37,
    primaryArchetype: WbPropArchetype.woodTarget,
    fillerArchetype: WbPropArchetype.woodBarrel,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _rubberStone,
  ),
  // 22 Heavy SMG
  const AngryWordsLoadout(
    profileIndex: 21,
    label: 'Heavy SMG',
    gun: AngryWordsGunKind.heavySmg,
    fireInterval: 0.072,
    bulletDamage: 2,
    pierce: 0,
    bulletRadius: 6.8,
    bulletSpeed: 1050,
    spread: 0.125,
    burstChance: 0.08,
    pelletCount: 1,
    recoilKick: 1.08,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 39,
    primaryArchetype: WbPropArchetype.ceramicJug,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _rubberStone,
  ),
  // 23 Ice Pistol
  const AngryWordsLoadout(
    profileIndex: 22,
    label: 'Ice Pistol',
    gun: AngryWordsGunKind.icePistol,
    fireInterval: 0.19,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 5.5,
    bulletSpeed: 900,
    spread: 0.035,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.72,
    element: AngryWordsBulletElement.ice,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 10,
    fillerCount: 38,
    primaryArchetype: WbPropArchetype.glassBottle,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: true,
    wallMix: _iceWater,
  ),
  // 24 Freeze Ray
  const AngryWordsLoadout(
    profileIndex: 23,
    label: 'Freeze Ray',
    gun: AngryWordsGunKind.freezeRay,
    fireInterval: 0.11,
    bulletDamage: 1,
    pierce: 1,
    bulletRadius: 5.9,
    bulletSpeed: 1040,
    spread: 0.04,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.78,
    element: AngryWordsBulletElement.ice,
    splashRadius: 0,
    homing: false,
    barrierCols: 14,
    barrierRows: 11,
    fillerCount: 40,
    primaryArchetype: WbPropArchetype.iceBlock,
    fillerArchetype: WbPropArchetype.waxBall,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _iceWaterDense,
  ),
  // 25 Flamethrower
  const AngryWordsLoadout(
    profileIndex: 24,
    label: 'Flamethrower',
    gun: AngryWordsGunKind.flamethrower,
    fireInterval: 0.092,
    bulletDamage: 1,
    pierce: 0,
    bulletRadius: 6.6,
    bulletSpeed: 680,
    spread: 0.2,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.7,
    element: AngryWordsBulletElement.fire,
    splashRadius: 30,
    homing: false,
    barrierCols: 14,
    barrierRows: 11,
    fillerCount: 41,
    primaryArchetype: WbPropArchetype.waxBall,
    fillerArchetype: WbPropArchetype.iceBlock,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodIce,
  ),
  // 26 Inferno Gun
  const AngryWordsLoadout(
    profileIndex: 25,
    label: 'Inferno Gun',
    gun: AngryWordsGunKind.inferno,
    fireInterval: 0.07,
    bulletDamage: 1,
    pierce: 1,
    bulletRadius: 6.9,
    bulletSpeed: 760,
    spread: 0.22,
    burstChance: 0.12,
    pelletCount: 2,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.fire,
    splashRadius: 42,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 43,
    primaryArchetype: WbPropArchetype.magmaOrb,
    fillerArchetype: WbPropArchetype.iceBlock,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _woodIceDense,
  ),
  // 27 Crossbow
  const AngryWordsLoadout(
    profileIndex: 26,
    label: 'Crossbow',
    gun: AngryWordsGunKind.crossbow,
    fireInterval: 0.38,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1320,
    spread: 0.016,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.2,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 44,
    primaryArchetype: WbPropArchetype.coconut,
    fillerArchetype: WbPropArchetype.pumpkin,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneMetal,
  ),
  // 28 Repeating Crossbow
  const AngryWordsLoadout(
    profileIndex: 27,
    label: 'Repeating Crossbow',
    gun: AngryWordsGunKind.repeatingCrossbow,
    fireInterval: 0.15,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 4.8,
    bulletSpeed: 1280,
    spread: 0.032,
    burstChance: 0.12,
    pelletCount: 1,
    recoilKick: 0.9,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 45,
    primaryArchetype: WbPropArchetype.pumpkin,
    fillerArchetype: WbPropArchetype.coconut,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneMetalDense,
  ),
  // 29 Hunting Rifle
  const AngryWordsLoadout(
    profileIndex: 28,
    label: 'Hunting Rifle',
    gun: AngryWordsGunKind.huntingRifle,
    fireInterval: 0.32,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1450,
    spread: 0.014,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.25,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 11,
    fillerCount: 46,
    primaryArchetype: WbPropArchetype.glassPane,
    fillerArchetype: WbPropArchetype.lightBulb,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _stoneMetalDense,
  ),
  // 30 Sniper Rifle
  const AngryWordsLoadout(
    profileIndex: 29,
    label: 'Sniper Rifle',
    gun: AngryWordsGunKind.sniper,
    fireInterval: 0.48,
    bulletDamage: 3,
    pierce: 3,
    bulletRadius: 4.5,
    bulletSpeed: 1680,
    spread: 0.008,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.55,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 48,
    primaryArchetype: WbPropArchetype.lightBulb,
    fillerArchetype: WbPropArchetype.glassPane,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalStone,
  ),
  // 31 Anti-Materiel
  const AngryWordsLoadout(
    profileIndex: 30,
    label: 'Anti-Materiel Rifle',
    gun: AngryWordsGunKind.antiMateriel,
    fireInterval: 0.55,
    bulletDamage: 4,
    pierce: 4,
    bulletRadius: 5.4,
    bulletSpeed: 1480,
    spread: 0.006,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.75,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 50,
    primaryArchetype: WbPropArchetype.steelPlate,
    fillerArchetype: WbPropArchetype.magnetSphere,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalStoneHeavy,
  ),
  // 32 Gauss Rifle
  const AngryWordsLoadout(
    profileIndex: 31,
    label: 'Gauss Rifle',
    gun: AngryWordsGunKind.gauss,
    fireInterval: 0.11,
    bulletDamage: 2,
    pierce: 3,
    bulletRadius: 4.2,
    bulletSpeed: 1880,
    spread: 0.028,
    burstChance: 0.08,
    pelletCount: 1,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 51,
    primaryArchetype: WbPropArchetype.magnetSphere,
    fillerArchetype: WbPropArchetype.steelPlate,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalStoneHeavy,
  ),
  // 33 Laser Pointer
  const AngryWordsLoadout(
    profileIndex: 32,
    label: 'Laser Pointer',
    gun: AngryWordsGunKind.laserPointer,
    fireInterval: 0.055,
    bulletDamage: 1,
    pierce: 2,
    bulletRadius: 2.6,
    bulletSpeed: 1680,
    spread: 0.004,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.32,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 15,
    barrierRows: 12,
    fillerCount: 52,
    primaryArchetype: WbPropArchetype.crystal,
    fillerArchetype: WbPropArchetype.neonOrb,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalGlass,
  ),
  // 34 Pulse Laser
  const AngryWordsLoadout(
    profileIndex: 33,
    label: 'Pulse Laser',
    gun: AngryWordsGunKind.pulseLaser,
    fireInterval: 0.048,
    bulletDamage: 1,
    pierce: 3,
    bulletRadius: 3.3,
    bulletSpeed: 1720,
    spread: 0.006,
    burstChance: 0.1,
    pelletCount: 1,
    recoilKick: 0.42,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 53,
    primaryArchetype: WbPropArchetype.oldTv,
    fillerArchetype: WbPropArchetype.crystal,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalIce,
  ),
  // 35 Beam Laser — emoji wall (visual skin; materials still apply)
  const AngryWordsLoadout(
    profileIndex: 34,
    label: 'Beam Laser',
    gun: AngryWordsGunKind.beamLaser,
    fireInterval: 0.034,
    bulletDamage: 2,
    pierce: 5,
    bulletRadius: 2.9,
    bulletSpeed: 1900,
    spread: 0.003,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.4,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 54,
    primaryArchetype: WbPropArchetype.emojiVariety,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalIceDense,
  ),
  // 36 Dual Plasma — animal emoji wall (visual skin; materials still apply)
  const AngryWordsLoadout(
    profileIndex: 35,
    label: 'Dual Plasma',
    gun: AngryWordsGunKind.plasmaPistol,
    fireInterval: 0.125,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 6.8,
    bulletSpeed: 1080,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 0.95,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 54,
    primaryArchetype: WbPropArchetype.emojiAnimal,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalIceDense,
  ),
  // 37 Twin Plasma Rifle
  const AngryWordsLoadout(
    profileIndex: 36,
    label: 'Twin Plasma Rifle',
    gun: AngryWordsGunKind.plasmaRifle,
    fireInterval: 0.085,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 7.2,
    bulletSpeed: 1180,
    spread: 0.058,
    burstChance: 0.18,
    pelletCount: 2,
    recoilKick: 1.05,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 55,
    primaryArchetype: WbPropArchetype.neonOrb,
    fillerArchetype: WbPropArchetype.neonTube,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _endgame,
  ),
  // 38 Triple Plasma Cannon
  const AngryWordsLoadout(
    profileIndex: 37,
    label: 'Triple Plasma Cannon',
    gun: AngryWordsGunKind.plasmaCannon,
    fireInterval: 0.18,
    bulletDamage: 3,
    pierce: 2,
    bulletRadius: 8.2,
    bulletSpeed: 980,
    spread: 0.048,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 24,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.neonTube,
    fillerArchetype: WbPropArchetype.neonOrb,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _endgameDense,
  ),
  // 39 Triple Railgun
  const AngryWordsLoadout(
    profileIndex: 38,
    label: 'Triple Railgun',
    gun: AngryWordsGunKind.railgun,
    fireInterval: 0.5,
    bulletDamage: 4,
    pierce: 4,
    bulletRadius: 4.2,
    bulletSpeed: 2050,
    spread: 0.018,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 1.85,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.metalGear,
    fillerArchetype: WbPropArchetype.batteryCell,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalStoneHeavy,
  ),
  // 40 Triple Coilgun — pure oil-barrel sea (assets/items/oilbarrel.png)
  const AngryWordsLoadout(
    profileIndex: 39,
    label: 'Triple Coilgun',
    gun: AngryWordsGunKind.coilgun,
    fireInterval: 0.05,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 5.0,
    bulletSpeed: 1580,
    spread: 0.085,
    burstChance: 0.2,
    pelletCount: 3,
    recoilKick: 0.85,
    element: AngryWordsBulletElement.plasma,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.oilDrum,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _metalStoneHeavy,
  ),
  // 41 Grenade Launcher
  const AngryWordsLoadout(
    profileIndex: 40,
    label: 'Grenade Launcher',
    gun: AngryWordsGunKind.grenadeLauncher,
    fireInterval: 0.36,
    bulletDamage: 3,
    pierce: 0,
    bulletRadius: 7.8,
    bulletSpeed: 740,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.45,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 44,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.fireworkShell,
    fillerArchetype: WbPropArchetype.powderKeg,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _fortress,
  ),
  // 42 RPG
  const AngryWordsLoadout(
    profileIndex: 41,
    label: 'RPG',
    gun: AngryWordsGunKind.rpg,
    fireInterval: 0.52,
    bulletDamage: 5,
    pierce: 0,
    bulletRadius: 8.8,
    bulletSpeed: 700,
    spread: 0.035,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.85,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 56,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.powderKeg,
    fillerArchetype: WbPropArchetype.fireworkShell,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _fortressDense,
  ),
  // 43 Homing Rocket
  const AngryWordsLoadout(
    profileIndex: 42,
    label: 'Homing Rocket',
    gun: AngryWordsGunKind.homingRocket,
    fireInterval: 0.46,
    bulletDamage: 4,
    pierce: 0,
    bulletRadius: 8.0,
    bulletSpeed: 660,
    spread: 0.06,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 1.6,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 52,
    homing: true,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.oilLamp,
    fillerArchetype: WbPropArchetype.rubberTire,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _fortressDense,
  ),
  // 44 Mini-Gun
  const AngryWordsLoadout(
    profileIndex: 43,
    label: 'Mini-Gun',
    gun: AngryWordsGunKind.minigun,
    fireInterval: 0.034,
    bulletDamage: 2,
    pierce: 1,
    bulletRadius: 5.0,
    bulletSpeed: 1340,
    spread: 0.145,
    burstChance: 0.18,
    pelletCount: 1,
    recoilKick: 0.88,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.concreteBlock,
    fillerArchetype: WbPropArchetype.brick,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _steelCurtain,
  ),
  // 45 Gatling
  const AngryWordsLoadout(
    profileIndex: 44,
    label: 'Gatling',
    gun: AngryWordsGunKind.gatling,
    fireInterval: 0.028,
    bulletDamage: 2,
    pierce: 2,
    bulletRadius: 5.4,
    bulletSpeed: 1400,
    spread: 0.11,
    burstChance: 0.2,
    pelletCount: 1,
    recoilKick: 0.98,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.rubberTire,
    fillerArchetype: WbPropArchetype.oilLamp,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _steelCurtain,
  ),
  // 46 Laser Tank Turret
  const AngryWordsLoadout(
    profileIndex: 45,
    label: 'Laser Tank Turret',
    gun: AngryWordsGunKind.laserTank,
    fireInterval: 0.036,
    bulletDamage: 2,
    pierce: 5,
    bulletRadius: 3.2,
    bulletSpeed: 1850,
    spread: 0.004,
    burstChance: 0,
    pelletCount: 1,
    recoilKick: 0.5,
    element: AngryWordsBulletElement.laser,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.goldTrophy,
    fillerArchetype: WbPropArchetype.bronzeBell,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _endgameDense,
  ),
  // 47 Hybrid Tank — hold-to-spray dual: laser + explosive
  const AngryWordsLoadout(
    profileIndex: 46,
    label: 'Hybrid Tank',
    gun: AngryWordsGunKind.tankCannon,
    fireInterval: 0.1,
    bulletDamage: 4,
    pierce: 0,
    bulletRadius: 9.2,
    bulletSpeed: 1020,
    spread: 0.055,
    burstChance: 0.12,
    pelletCount: 2,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 42,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.stoneStatue,
    fillerArchetype: WbPropArchetype.obsidianGem,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _endgameDense,
  ),
  // 48 Twin Tank Guns
  const AngryWordsLoadout(
    profileIndex: 47,
    label: 'Twin Tank Guns',
    gun: AngryWordsGunKind.twinTank,
    fireInterval: 0.4,
    bulletDamage: 3,
    pierce: 0,
    bulletRadius: 8.4,
    bulletSpeed: 900,
    spread: 0.08,
    burstChance: 0,
    pelletCount: 2,
    recoilKick: 1.8,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 46,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.bronzeBell,
    fillerArchetype: WbPropArchetype.goldTrophy,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _doomsdayWall,
  ),
  // 49 Siege Artillery — triple barrel
  const AngryWordsLoadout(
    profileIndex: 48,
    label: 'Siege Artillery',
    gun: AngryWordsGunKind.siege,
    fireInterval: 0.66,
    bulletDamage: 5,
    pierce: 0,
    bulletRadius: 9.2,
    bulletSpeed: 720,
    spread: 0.055,
    burstChance: 0,
    pelletCount: 3,
    recoilKick: 2.1,
    element: AngryWordsBulletElement.explosive,
    splashRadius: 66,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.obsidianGem,
    fillerArchetype: WbPropArchetype.stoneStatue,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _doomsdayWall,
  ),
  // 50 Doomsday MG — 5-barrel chaingun vs all-stone wall (2-hit crack→shatter)
  const AngryWordsLoadout(
    profileIndex: 49,
    label: 'Doomsday MG',
    gun: AngryWordsGunKind.doomsdayMg,
    fireInterval: 0.03,
    bulletDamage: 1,
    pierce: 3,
    bulletRadius: 6.0,
    bulletSpeed: 1480,
    spread: 0.1,
    burstChance: 0.18,
    pelletCount: 5,
    recoilKick: 1.35,
    element: AngryWordsBulletElement.normal,
    splashRadius: 0,
    homing: false,
    barrierCols: 16,
    barrierRows: 12,
    fillerCount: 56,
    primaryArchetype: WbPropArchetype.graniteBlock,
    fillerArchetype: null,
    primaryRatio: 0.7,
    usesHammer: false,
    wallMix: _doomsdayMgWall,
  ),
];
